class_name GameMode
extends RhythmGameStateNode

#TODO: obselete? this can get refactored out
@export var player: Player

@export var rules : GameModeRules
#i think this can probably be made in onready?
@onready var blackboard : Blackboard = Blackboard.new()


func Start():
	pass


func MoveToNextPhase():
	pass
	
func End():
	pass
	

#win/lose condition, could be as simple as a key being pressed
func CheckEndCondition():
	pass

#look at the report generated by the player and figure out what to do next
func HandlePlayerPhaseEnd():
	pass


func _on_metronome_beat_update(timeInBeats) -> void:
	pass # Replace with function body.
