class_name GameMode
extends Node


#so game mode should become an abstract class
#for now this will be for sketching and i can abstract it later
#all game modes need to start

#all game modes need to have win or end conditions

#all game modes are gonna have phases
#yada yada

#so start is going to initially create a looping player sequence

@export var player: Node

func Start():
	pass
	
func End():
	pass
	

#win/lose condition, could be as simple as a key being pressed
func CheckEndCondition():
	pass

#look at the report generated by the player and figure out what to do next
func HandlePlayerPhaseEnd():
	pass
